eduzz/houston

.eslintrc.json, components/Button/index.tsx, components/ThemeProvider/_default/index.ts, components/ThemeProvider/index.tsx, components/ThemeProvider/orbita/index.ts, components/ThemeProvider/select/index.ts, package.json, yarn.lock
- Adicionei um map para simplificar o componente de button
- Coloquei um memo para reduzir renderizações desnecessárias
- Coloquei o plugin de organização de imports
=> property map in the buttom component

.github/workflows/pull-request.yml, README.md
Signed-off-by: danieloprado <danielprado.ad@gmail.com>
=> pull request action

CONTRIBUTING.md, README.md, yarn.lock
=> Improve minor spelling corrections and header level

dev/src/components/Pages/Grid/index.tsx, dev/src/components/Pages/Typography.tsx, packages/ui-components/ThemeProvider/_default/variables.ts
Trocando de confortable para comfortable
=> corrigindo comfortable escrito errado no Typography

src/packages/ui-components/Forms/internals/RadioBase.tsx
Se passarmos um valor boolean para o componente, no e.target.value ele é convertido para string e passa 'true' ou 'false' para o formik, essa foi a solução que pensei
=> fix radion boolean value

src/packages/ui-components/Table/Row/index.tsx
Não exibe o menu de opções quando houver somente uma ação e permite escolher o ícone para essa opção
=> adiciona condições para quando existir apenas uma ação

src/packages/forms/useForm.tsx
=> fix: submit now uses onSubmit last created value

src/packages/core/formAdapter.ts, src/packages/forms/useForm.tsx
=> Adicionado setFieldTouched e setErrors no useForm

src/packages/icons/index.mdx, src/packages/icons/index.tsx
Ultimamente tenho usado muito os ícones do Houston e ai pensei na proposta:
Ao clicar no ícone copiar para o clipboard:
`import Icon from '@eduzz/houston-icons/Icon';`
Ajuda bastante :>
=> feat(icons): add copy to clipboard on icon click

src/packages/icons/interfaces/index.ts, src/packages/ui-components/Showcase/Showcase.tsx, src/packages/ui-components/Showcase/index.mdx, src/packages/ui-components/Showcase/internals/CallToActions/index.tsx, src/packages/ui-components/Showcase/internals/Header/index.tsx, src/packages/ui-components/Showcase/internals/Steps/index.tsx
O Showcase em telas menores estava quebrando, coloquei um `overflow: auto` no content pra resolver.
_Mudei umas outras coisinhas também_
=> fix(showcase): card content height in small screens

src/pages/contributing.mdx
Adicionei um novo texto explicando melhor como vai funcionar o esquema de commits, para o pessoal já ir se acostumando e dps pra dar uma ajuda pra nós na hora de criar o versionamento.
=> Docs contribuing commit

src/pages/contributing.mdx, src/pages/ui-components/Button/index.mdx, src/pages/ui-components/Button/index.tsx, src/pages/ui-components/styles/ThemeProvider/_generator/variables.ts
Conforme #267, adicionei novas opções de cores.
=> feat(button): adicionado opções de cores

src/dev/package.json, src/pages/ui-components/Toast/Container.tsx, src/pages/ui-components/Toast/styles.ts
=> fix(toast): removed big icon

.github/workflows/beta.yml, package.json, src/pages/core/package.json, src/pages/core/tsconfig.json, src/pages/eslint-config/package.json, src/pages/experimental/package.json, src/pages/experimental/tsconfig.json, src/pages/forms/package.json, src/pages/forms/tsconfig.json, src/pages/hooks/config.tsx, src/pages/hooks/package.json, src/pages/hooks/tsconfig.json, src/pages/icons/package.json, src/pages/icons/tsconfig.json, src/pages/ui-components/package.json, src/pages/ui-components/tsconfig.json
=> fix(hooks): fix rxjs import from config

src/pages/ui-components/Layout/Content/index.tsx, src/pages/ui-components/Table/Pagination/index.tsx
Aumentei a largura do container do componente de paginação e corrigi o scroll do Layout.Content.
=> Ajustes do Layout

src/pages/ui-components/Typography/Caption/index.tsx, src/pages/ui-components/Typography/Heading/index.tsx, src/pages/ui-components/Typography/Paragraph/index.tsx, src/pages/ui-components/Typography/Subtitle/index.tsx, src/pages/ui-components/Typography/index.mdx, src/pages/ui-components/Typography/index.tsx
Não consegui achar uma maneira melhor de tipar essa prop, mas isso resolve.
=> Adiciona mais opções na Tipografia

src/pages/tokens/index.ts, src/pages/tokens/types.ts, src/pages/tokens/variables/border.ts, src/pages/tokens/variables/breakpoints.ts, src/pages/tokens/variables/feedbackColor.ts, src/pages/tokens/variables/font.ts, src/pages/tokens/variables/line.ts, src/pages/tokens/variables/neutralColor.ts, src/pages/tokens/variables/opacity.ts, src/pages/tokens/variables/shadow.ts, src/pages/tokens/variables/spacing.ts, src/pages/tokens/variables/utils.ts, src/pages/ui-components/Avatar/index.tsx, src/pages/ui-components/Breadcrumb/Link/index.tsx, src/pages/ui-components/Breadcrumb/index.tsx, src/pages/ui-components/Image/Thumbnail/index.tsx, src/pages/ui-components/Layout/Sidebar/Logo/index.tsx, src/pages/ui-components/Layout/Sidebar/Wrapper/index.tsx, src/pages/ui-components/Spinner/index.tsx, src/pages/ui-components/Table/styles.tsx, src/pages/ui-components/ThemeProvider/_generator/components.ts, src/pages/ui-components/ThemeProvider/_generator/index.ts, src/pages/ui-components/ThemeProvider/_generator/typography.ts, src/pages/ui-components/Typography/index.mdx, src/pages/ui-components/Typography/index.tsx
Galera, segue o PR que atualiza nosso padrão de PX para REM.
Acredito que esse PR deve apontar para master mesmo, correto?
=> Atualiza padrão de unidade de tokens e componentes para REM

src/pages/ui-components/Layout/Sidebar/Logo/index.tsx, src/pages/ui-components/Typography/index.tsx
Remove a especificidade do BEM para que possamos conseguir sobrescrever os estilos.
=> Fix sidebar refactor typography

src/pages/ui-components/Forms/DatePicker/index.tsx, src/pages/ui-components/Forms/_utils/CheckboxRadio.tsx, src/pages/ui-components/Forms/_utils/Fieldset.tsx, src/pages/ui-components/ThemeProvider/index.tsx
Ajustezinhos feitos:
- Não exibe hover nos campos quando desabilitado;
- DatePicker não funcionava por conta do import do LocalizationProvider;
- DatePicker exibia mensagem de erro por não ter os rendlers de onBlur e onChange;
- Prop helperText aceita React.ReactNode, porque em muitos casos temos alguma parte do texto que é clicável;
=> Some adjustments

src/pages/eslint-config/configs/typescript.js, src/pages/eslint-config/index.js, src/pages/hooks/config.tsx, src/pages/hooks/useObservablePaginated/index.tsx, src/pages/hooks/usePromisePaginated/index.tsx, src/pages/ui-components/Breadcrumb/Link/index.tsx, src/pages/ui-components/Forms/Select/context.ts, src/pages/ui-components/Layout/Sidebar/MenuItem/index.tsx, src/pages/ui-components/Popover/context.ts, src/pages/ui-components/Toast/index.tsx
Novas Regras:
* força public/private em métodos de classes.
* força a ordem correta de private/publics dentro de uma classe.
* remove a regra de interfaces começarem com a letra "I"
* força uma melhor convençao de nomes para variáveis.
=> feat(eslint): melhora as regras do eslint focando no typescript

src/pages/ui-components/Badge/index.mdx, src/pages/ui-components/Badge/index.tsx
Figma: https://www.figma.com/file/WJWEph4jRV7uuVe4e9Pj13/Core-components-handoff?node-id=3412%3A68717
=> Componente Badge

src/pages/ui-components/Card/index.mdx, src/pages/ui-components/Card/index.tsx
[Link do Figma](https://www.figma.com/file/WJWEph4jRV7uuVe4e9Pj13/Core-components-handoff?node-id=5269%3A104487).
=> Card Component

src/pages/ui-components/Dropdown/Root.tsx, src/pages/ui-components/Dropdown/index.mdx, src/pages/ui-components/Dropdown/index.tsx, src/pages/ui-components/Popover/Root.tsx, src/pages/ui-components/Popover/index.tsx, src/pages/ui-components/package.json
Fala guys... Não lembro como decidimos nomear esse componente, mas momentaneamente da pra deixar assim de boa!!
Ele é uma cópia do Tooltip com algumas diferenças. Não me apeguei a fazer muito completo esse componente por que temos várias duvidas sobre ele e a lib que usamos vamos precisar migra-lá para uma versão mais nova refatorada.
[demo-dropdown.webm](https://user-images.githubusercontent.com/22228470/187769979-f467b850-a6ca-4139-9e12-f730a969cac1.webm)
[Link do Figma](https://www.figma.com/file/WJWEph4jRV7uuVe4e9Pj13/Core-components-handoff?node-id=775%3A20263).
=> Componente de Dropdown/Popover

src/pages/ui-components/Layout/Sidebar/Group/index.tsx, src/pages/ui-components/Layout/Topbar/Apps/index.tsx
=> Add topbar ids

src/pages/ui-components/Layout/Content/index.tsx, src/pages/ui-components/Layout/Sidebar/Group/index.tsx, src/pages/ui-components/Layout/Sidebar/Item/index.tsx
=> Atualizações no Layout

src/dev/src/App.tsx, src/pages/ui-components/Icons/Apps.tsx, src/pages/ui-components/Icons/ChevronLeft.tsx, src/pages/ui-components/Icons/ChevronRight.tsx, src/pages/ui-components/Icons/Close.tsx, src/pages/ui-components/Icons/Menu.tsx, src/pages/ui-components/Layout/Topbar/Action/index.tsx, src/pages/ui-components/Layout/Topbar/Actions/context.ts, src/pages/ui-components/Layout/Topbar/Actions/index.tsx, src/pages/ui-components/Layout/Topbar/Apps/Dropdown/index.tsx, src/pages/ui-components/Layout/Topbar/Apps/index.tsx, src/pages/ui-components/Layout/Topbar/Logo/index.tsx, src/pages/ui-components/Layout/Topbar/User/index.tsx, src/pages/ui-components/Layout/Topbar/index.tsx, src/pages/ui-components/ThemeProvider/index.tsx, src/pages/ui-components/hooks/useClickOutside.tsx
https://user-images.githubusercontent.com/7683575/204037422-bd8b344e-54bd-46e5-b477-fe315b399e56.mov
Adiciona o comportamento de expand quando tiver mais de 1 item de action.
=> feat: add mobile actions expand
